### ISSUE TITLE
Android App crash with intelXDK 2894

### ISSUE THREAD

**Issue by yetanotherportfolio** [admob-google/admob-cordova#17]
I'm using the intel XDK 2894 and when building the Android Crosswalk version, calling admob.showBanner(admob.BannerSize.BANNER,admob.Position.TOP_APP); will make the whole app crash.

**Comment by admob-google** [comment]
any log?

**Comment by yetanotherportfolio** [comment]
intel XDK is not showing any logs (even in debug mode), it just say that the app crashed. (I'm using a Nexus 5, android version 6.0.1)

**Comment by arjankuijpers** [comment]
which version of the plugin are you using ?.

**Comment by yetanotherportfolio** [comment]
I tried the current master branch and 5.0.4, they both have the same behavior.

**Comment by admob-google** [comment]
android system logcat log

**Comment by yetanotherportfolio** [comment]
got this with adb logcat:

```
01-31 10:40:28.522 28920 28920 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.RelativeLayout.addView(android.view.View, android.view.ViewGroup$LayoutParams)' on a null object reference
01-31 10:40:28.522 28920 28920 E AndroidRuntime: 	at com.admob.cordova.plugin.AdmobAdPlugin$2.run(AdmobAdPlugin.java:228)
01-31 10:40:28.522 28920 28920 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
01-31 10:40:28.522 28920 28920 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
01-31 10:40:28.522 28920 28920 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
01-31 10:40:28.522 28920 28920 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
01-31 10:40:28.522 28920 28920 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-31 10:40:28.522 28920 28920 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
01-31 10:40:28.522 28920 28920 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by admob-google** [comment]
Great ,will release a fixed version soon

**Comment by admob-google** [comment]
have you call initAdmob before call showBanner?

**Comment by admob-google** [comment]
new version submit

**Comment by admob-google** [comment]
upgraded
