### ISSUE TITLE
Plugin is crashing app

### ISSUE THREAD

**Issue by fmbuthia** [admob-google/admob-cordova#7]
The new plugin version 5.0.1 is crashing my application. I had to use version 3.0.0. I don't have crash logs at the moment but will add them when I encounter the issue again.

**Comment by jamminjames** [comment]
Crashing mine also. Will try earlier version.

**Comment by admob-google** [comment]
any log?ios or android?

**Comment by jamminjames** [comment]
Android for me. Is there a way to get an error log off an android?

**Comment by admob-google** [comment]
can you send your demo code and apk that crash to me gooogleadmob@gmail.com

**Comment by CrankyMero** [comment]
I get his when building my app

"Error build Android package: Index was out of range. Must be non-negative and less than the size of the collection."

I've been building my app with DevExtreme

**Comment by admob-google** [comment]
have you try the demo app? can you send your  apk that crash to me gooogleadmob@gmail.com to run ?

**Comment by admob-google** [comment]
phonegap plugin version 5.0.3

**Comment by CrankyMero** [comment]
I get an error when trying to create the template it says its not there

![admob503](https://cloud.githubusercontent.com/assets/6289721/8781338/36f182fe-2ec3-11e5-8b02-5365179c5c84.png)

**Comment by admob-google** [comment]
retry

**Comment by CrankyMero** [comment]
Got this error it did find it, but im not sure what was the error.

![admob unknown error](https://cloud.githubusercontent.com/assets/6289721/8829776/5e0dbdae-304d-11e5-93ab-ee44e91ca7bd.png)

**Comment by admob-google** [comment]
the following error? what is the following error,not infomation  detail of it? have you try cordova ?

**Comment by JoeSchr** [comment]
Sadly this is still true. I just try to cache and show a Interstitial Ad. Here is the log, get back to me if you need anything more.

```
I/Ads     (16924): Ad finished loading.

D/AndroidRuntime(16924): Shutting down VM

E/AndroidRuntime(16924): FATAL EXCEPTION: main

E/AndroidRuntime(16924): Process: com.myapp.studio, PID: 16924

E/AndroidRuntime(16924): java.lang.IncompatibleClassChangeError: The method 'void org.apache.cordova.CordovaWebView.loadUrl(java.lang.String)' was expected to be of type interface but instead was found to be of type virtual (declaration of 'java.lang.reflect.ArtMethod' appears in /system/framework/core-libart.jar)

E/AndroidRuntime(16924): 	at com.admob.cordova.plugin.BDInterstitialAdListener.fireEvent(BDInterstitialAdListener.java:19)

E/AndroidRuntime(16924): 	at com.admob.cordova.plugin.BDInterstitialAdListener.onAdLoaded(BDInterstitialAdListener.java:42)

E/AndroidRuntime(16924): 	at com.google.android.gms.ads.internal.client.zzc.onAdLoaded(Unknown Source)

E/AndroidRuntime(16924): 	at com.google.android.gms.ads.internal.client.zzm$zza.onTransact(Unknown Source)

E/AndroidRuntime(16924): 	at android.os.Binder.transact(Binder.java:380)

E/AndroidRuntime(16924): 	at com.google.android.gms.ads.internal.client.l.c(SourceFile:152)

E/AndroidRuntime(16924): 	at com.google.android.gms.ads.internal.a.q(SourceFile:697)

E/AndroidRuntime(16924): 	at com.google.android.gms.ads.internal.t.q(SourceFile:277)

E/AndroidRuntime(16924): 	at com.google.android.gms.ads.internal.a.b(SourceFile:369)

E/AndroidRuntime(16924): 	at com.google.android.gms.ads.internal.b.b(SourceFile:152)

E/AndroidRuntime(16924): 	at com.google.android.gms.ads.internal.o.f.a(SourceFile:130)

E/AndroidRuntime(16924): 	at com.google.android.gms.ads.internal.o.h.run(SourceFile:115)

E/AndroidRuntime(16924): 	at android.os.Handler.handleCallback(Handler.java:739)

E/AndroidRuntime(16924): 	at android.os.Handler.dispatchMessage(Handler.java:95)

E/AndroidRuntime(16924): 	at android.os.Looper.loop(Looper.java:135)

E/AndroidRuntime(16924): 	at android.app.ActivityThread.main(ActivityThread.java:5254)

E/AndroidRuntime(16924): 	at java.lang.reflect.Method.invoke(Native Method)

E/AndroidRuntime(16924): 	at java.lang.reflect.Method.invoke(Method.java:372)

E/AndroidRuntime(16924): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)

E/AndroidRuntime(16924): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

W/ActivityManager(  637):   Force finishing activity 1 com.myapp.studio/.CordovaApp

W/debuggerd(17279): type=1400 audit(0.0:140812): avc: denied { execute_no_trans } for path="/system/bin/toolbox" dev="mmcblk0p22" ino=413 scontext=u:r:debuggerd:s0 tcontext=u:object_r:system_file:s0 tclass=file

W/DropBoxManagerService(  637): Dropping: data_app_crash (1754 > 0 bytes)

W/debuggerd(17280): type=1400 audit(0.0:140813): avc: denied { execute_no_trans } for path="/system/xbin/supolicy" dev="mmcblk0p22" ino=1656 scontext=u:r:debuggerd:s0 tcontext=u:object_r:system_file:s0 tclass=file

W/debuggerd(17281): type=1400 audit(0.0:140814): avc: denied { execute_no_trans } for path="/system/bin/toolbox" dev="mmcblk0p22" ino=413 scontext=u:r:debuggerd:s0 tcontext=u:object_r:system_file:s0 tclass=file

W/debuggerd(17277): type=1400 audit(0.0:140815): avc: denied { search } for name="eu.chainfire.stickmount" dev="mmcblk0p30" ino=417596 scontext=u:r:debuggerd:s0 tcontext=u:object_r:app_data_file:s0 tclass=dir

```

**Comment by JoeSchr** [comment]
Some more logs
```
--------- beginning of crash

E/AndroidRuntime( 7616): FATAL EXCEPTION: main

E/AndroidRuntime( 7616): Process: com.mymysteriousapp.studio, PID: 7616

E/AndroidRuntime( 7616): java.lang.IncompatibleClassChangeError: The method 'void org.apache.cordova.CordovaWebView.loadUrl(java.lang.String)' was expected to be of type interface but instead was found to be of type virtual (declaration of 'java.lang.reflect.ArtMethod' appears in /system/framework/core-libart.jar)

E/AndroidRuntime( 7616): 	at com.admob.cordova.plugin.BDInterstitialAdListener.fireEvent(BDInterstitialAdListener.java:19)

E/AndroidRuntime( 7616): 	at com.admob.cordova.plugin.BDInterstitialAdListener.onAdLoaded(BDInterstitialAdListener.java:42)

E/AndroidRuntime( 7616): 	at com.google.android.gms.ads.internal.client.zzc.onAdLoaded(Unknown Source)

E/AndroidRuntime( 7616): 	at com.google.android.gms.ads.internal.client.zzm$zza.onTransact(Unknown Source)

E/AndroidRuntime( 7616): 	at android.os.Binder.transact(Binder.java:380)

E/AndroidRuntime( 7616): 	at com.google.android.gms.ads.internal.client.l.c(SourceFile:152)

E/AndroidRuntime( 7616): 	at com.google.android.gms.ads.internal.a.q(SourceFile:697)

E/AndroidRuntime( 7616): 	at com.google.android.gms.ads.internal.t.q(SourceFile:277)

E/AndroidRuntime( 7616): 	at com.google.android.gms.ads.internal.a.b(SourceFile:369)

E/AndroidRuntime( 7616): 	at com.google.android.gms.ads.internal.b.b(SourceFile:152)

E/AndroidRuntime( 7616): 	at com.google.android.gms.ads.internal.o.f.a(SourceFile:130)

E/AndroidRuntime( 7616): 	at com.google.android.gms.ads.internal.o.h.run(SourceFile:115)

E/AndroidRuntime( 7616): 	at android.os.Handler.handleCallback(Handler.java:739)

E/AndroidRuntime( 7616): 	at android.os.Handler.dispatchMessage(Handler.java:95)

E/AndroidRuntime( 7616): 	at android.os.Looper.loop(Looper.java:135)

E/AndroidRuntime( 7616): 	at android.app.ActivityThread.main(ActivityThread.java:5254)

E/AndroidRuntime( 7616): 	at java.lang.reflect.Method.invoke(Native Method)

E/AndroidRuntime( 7616): 	at java.lang.reflect.Method.invoke(Method.java:372)

E/AndroidRuntime( 7616): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)

E/AndroidRuntime( 7616): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

W/DropBoxManagerService(  637): Dropping: data_app_crash (1754 > 0 bytes)

W/ActivityManager(  637):   Force finishing activity 1 com.mymysteriousapp.studio/.CordovaApp

W/ActivityManager(  637): Activity pause timeout for ActivityRecord{2ad89aa2 u0 com.mymysteriousapp.studio/.CordovaApp t5936 f}

D/WifiService(  637): Client connection lost with reason: 4

I/ActivityManager(  637): Process free.reddit.news (pid 30127) has died

I/ActivityManager(  637): Process org.kman.WifiManager (pid 31305) has died

I/ActivityManager(  637): Process com.google.android.gms:car (pid 4365) has died

I/ActivityManager(  637): Process com.android.vending (pid 4305) has died

V/NotificationService(  637): notifications are disabled by AppOps for com.mobidia.android.mdm

E/NotificationService(  637): Suppressing notification from package com.mobidia.android.mdm by user request.

I/ActivityManager(  637): Process com.google.android.apps.photos (pid 3953) has died

I/ActivityManager(  637): Process com.google.android.gms.wearable (pid 4393) has died

I/ActivityManager(  637): Process android.process.acore (pid 31434) has died

I/ActivityManager(  637): Start proc 4692:android.process.acore/u0a3 for content provider com.android.providers.contacts/.CallLogProvider

I/ActivityManager(  637): Start proc 4713:com.google.android.apps.photos/u0a220 for broadcast com.google.android.apps.photos/com.google.android.libraries.social.gcm.GcmBroadcastReceiver

I/WindowState(  637): WIN DEATH: Window{2026ffb2 u0 com.mymysteriousapp.studio/com.mymysteriousapp.studio.CordovaApp}

E/libprocessgroup(  637): failed to kill 1 processes for processgroup 7616

I/ActivityManager(  637): Process com.mymysteriousapp.studio (pid 7616) has died

```

**Comment by admob-google** [comment]
Incompatible versions Error,what is your cordova version

**Comment by JoeSchr** [comment]
I'm building with Intel XDK, it says: "Building a Cordova 4.1.2 application."

**Comment by CrankyMero** [comment]
Im building it with DevExtreme and im using Cordova 3.7.0

On Tue, Aug 18, 2015 at 7:58 AM, JoeSchr <notifications@github.com> wrote:

> I'm building with Intel XDK, it says: "Building a Cordova 4.1.2
> application."
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/admob-google/admob-cordova/issues/7#issuecomment-132240041>
> .
>



-- 
*Roemer Pompa Parra*

*ISC Servicios y SolucionesCel: 653-113-4668*
*Skype: roemer.pompa*

**Comment by admob-google** [comment]
fix install from git   https://github.com/admob-google/admob-cordova.git

**Comment by souly1** [comment]
I have same issue, crashes when admit.banner called. Ionic app on Crosswalk, tried to install from git (didn't work, I needed to copy it local and play around with it a bit) and still crashes

**Comment by admob-google** [comment]
any crash log?

**Comment by souly1** [comment]
Sorry, just moved to a different plugin...

**Comment by admob-google** [comment]
fixed ,enjoy it
